spring:
  datasource:
    url: jdbc:mysql://localhost/sistema-de-viajes?serverTimezone=UTC
    username: root 
    password: 
    initialization-mode: never
  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false